### PR TITLE
Bonnie 820 cql translate exception

### PR DESCRIPTION
**Pull request by alexanderelliott121**
Front end support for cql translation error reporting.
JIRA test can be found at: https://jira.mitre.org/browse/BONNIE-831

### CODE REVIEW

**Review by holmesie — APPROVED** [review]
Looks good

**Review by c-monkey — APPROVED** [review]
tested using https://github.com/projecttacoma/bonnie_bundler/pull/92

looks good

**Review by edeyoung — CHANGES_REQUESTED** [review]
ON HOLD until we do a 1.2.9 deployment onto Bonnie-Alpha and run the rake task.

**Comment by c-monkey** [comment]
we don't know when we can incorporate this fix

**Pull request closed without merging**
