### PR TITLE
BONNIE-776 Fixes strat selection after save issue.

### PR DESCRIPTION
**Pull request by alexanderelliott121**
JIRA Ticket: https://jira.mitre.org/browse/BONNIE-776
JIRA Test: https://jira.mitre.org/browse/BONNIE-876

### CODE REVIEW

**Review by jbradl11 — APPROVED** [review]
Ran Jira test locally. Looks good.

**Review by hossenlopp — APPROVED** [review]

**Comment by hossenlopp** [comment]
`bundle exec rake test` and `bundle exec rake teaspoon` both passed locally. Travis' mongod is having issues with our tests out of nowhere.

**Comment by edeyoung** [comment]
Given that travis is borking after just a comment was added, had passed previously, and appears to failing for reasons unrelated to this PR, I am approving and merging.

**Comment by mayerm94** [comment]
I checked out the failing travis build. The failing tests are due to that duplicate key issue because mongo was not successfully dropping the collections before each test. My solution to this was in test/test_helper.rb change  
```
def dump_database
    Mongoid.default_session.collections.each do |c|
      c.drop()
    end
  end
```
to.....
```
dump_database
    Mongoid.default_session.drop()
 end
```

**Comment by hossenlopp** [comment]
@mayerm94 But why is it just suddenly happening out of nowhere? Does this fix work for all versions of mongoid and mongo though?

**Comment by mayerm94** [comment]
@hossenlopp I know this is not a good answer, but it seems like it starts happening randomly. It started happening randomly on my machine and on Sam's machine. I think it is a problem with newer versions of mongo (possibly due to a deprecated function?). My machine no longer behaves like this, I just wanted to offer what my solution was when it acted up.

**Pull request merged**
