### PR TITLE
Enable date shifting a user's patient records via rake task

### PR DESCRIPTION
**Pull request by jtferns**
### Story
- https://www.pivotaltracker.com/story/show/63411726
### Notes
- added `rake bonnie:patients:date_shift` rake task with `EMAIL, DIR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS` arguments
  - Use `EMAIL` to denote the user to scope the date_shift for all associated patients' source data criteria; first user by default.
  - Use `DIR` to denote direction [forward, backward]; direction is forward by default.
  - Use `SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS` to denote time offset [###]; offsets are 0 by default.
- updated Patient Data Criteria model to use `bonnie.measurePeriod` when specifying the default dates for a dropped data criteria in the patient builder
- passed in bonnie.yml's `measure_start_period` into export action for the users_controller when exporting a user bundle within the admin users view
- specified an `effective_date` variable in the measure javascript containing bonnie.yml's `measure_start_period` (with computation for the end date)

### CODE REVIEW

**Comment by pkmitre** [comment]
Shouldn't we shift the patient date of birth and date of death as well? Those generally interact with the measurement period.

**Comment by jtferns** [comment]
Ah right, they can and probably should be shifted accordingly, as well.

**Comment by andrequina** [comment]
We also need to shift any fields that are date related... i.e., admission date/time, departure date/time, incision date/time, etc.  The fields should have a field_type of timestamp or nested_timestamp.

see:

https://github.com/projectcypress/health-data-standards/blob/master/lib/hqmf-model/data_criteria.rb

**Comment by jtferns** [comment]
Patient data criteria field values with timestamp values are now properly date-shifted via 911ef7dad743e4e5542bfc6022e8ae1737d7a836

**Comment by pkmitre** [comment]
It looks like adding 1.year actually adds 365.25 days, which isn't exactly what we want because it changes the time; we want the time to stay the same. We'll have to figure out another approach that accounts for leap year.

**Comment by jtferns** [comment]
a50263fcebba35a60870ab336738913cf7b60197 uses <code>Time.advance</code> instead of the <code>+</code>/<code>-</code> operators for shifting the dates, which are more [precise](http://api.rubyonrails.org/classes/Time.html#method-i-advance) and should not affect the other time sections (the only exception is a leap year, where 02/29/2012 shifts to 02/28/2013 for <code>YEARS=1</code>, etc.).

**Pull request merged**
