### PR TITLE
Cql4bonine 1049 expected values

### PR DESCRIPTION
**Pull request by edeyoung**
This uses the code for updated expected value structure from the measure history code.

JIRA: https://jira.mitre.org/browse/BONNIE-1055

### CODE REVIEW

**Comment by mulcahyk** [comment]
Are there JIRA tests that go along with this?  Do you have a sample measure to work with?

**Comment by c-monkey** [comment]
@mulcahyk Links are not in this github PR, but the referenced internal JIRA ticket has a lot of info, and the referenced external ticket has an attached measure.

**Review by mulcahyk — APPROVED** [review]
Performing as expected.

**Review by c-monkey — APPROVED** [review]
Verified bug with cql4bonnie branch, switch to this branch and bug fixed.

**Comment by hossenlopp** [comment]
Regression test script passes with no changes.

**Pull request merged**
