### PR TITLE
Use VSAC latest profile API call to choose and mark latest profile

### PR DESCRIPTION
**Pull request by hossenlopp**
This discontinues the usage of the 'Latest eCQM' profile. It makes use of the new VSAC utility call to fetch the latest profile for the CMS eCQM program. The latest profile is marked as such in the UI in the drop down.

- [x] ❗️Gemfile must be updated before merging, this can be done after https://github.com/projecttacoma/bonnie_bundler/pull/145 is merged.

screen shot 2018-05-23 at 1 23 26 pm
screen shot 2018-05-23 at 1 23 34 pm

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1502 https://jira.mitre.org/browse/BONNIE-1508
- [x] JIRA ticket links to this PR
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [x] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 

Branch | Back End Coverage | Front End Coverage
-- | -- | --
master | 1738 / 1950 LOC (89.13%) covered. | Statements   : 58.43% ( 7032/12035 )<br>Branches     : 42.16% ( 1884/4469 )<br>Functions    : 48.85% ( 1167/2389 )<br>Lines        : 56.25% ( 6306/11210 )
new branch | 1738 / 1950 LOC (89.13%) covered. | Statements   : 58.45% ( 7037/12040 )<br>Branches     : 42.21% ( 1888/4473 )<br>Functions    : 48.85% ( 1167/2389 )<br>Lines        : 56.27% ( 6311/11215 )

- [x] Automated regression test(s) pass N/A Does not touch calculation code.

If JIRA tests were used to supplement or replace automated tests: N/A
- [x] JIRA test links: N/A
- [x] Justification for using JIRA tests: N/A
- [x] JIRA tests have been added to sprint N/A

**Reviewer 1:**

Name: @holmesie
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA tests have been run and pass
- [x] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:** 

Name: @mayerm94
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA tests have been run and pass
- [x] You agree with the justification for use of JIRA tests or have provided input on why you disagree

### CODE REVIEW

**Review by holmesie — DISMISSED** [review]
Changes make sense. Approved.

**Review by mayerm94 — DISMISSED** [review]
Looks great!

**Review by holmesie — APPROVED** [review]
Still looks good. Re-approved.

**Review by mayerm94 — APPROVED** [review]
Re-approve --gemfile update looks good

**Pull request merged**
