### PR TITLE
Fix for highlight suppression on multiple population measures

### PR DESCRIPTION
**Pull request by hossenlopp**
On multiple population set measures, changing population sets created new views without the suppression setting persisted. This fix passes the suppression option to the PopulationsLogic view so it can be properly passed to the PopulationLogic views when the use changes the population set.

Test this by using any measure with multiple population sets and switching to a measure other than the first one and rolling over the measure logic. If no errors result, then it was properly suppressed. To ensure suppression doesn't go too far, test the data element highlighting in the patient builder.

### CODE REVIEW

**Comment by jbradl11** [comment]
Considering we are now adding this suppression check everywhere, should we add it in patient_bank_view.js.coffee? Where its creating PopulationLogic and PopulationsLogic views. I don't believe it makes a difference in this case. I was mainly thinking this would act as a sanity check.

**Comment by alexanderelliott121** [comment]
I've tested it, and I'm not seeing the flood of error messages.
I concur if there are other places where the method is called they should be updated, for consistencies' sake.

**Review by jbradl11 — APPROVED** [review]
Looks good.

**Review by c-monkey — APPROVED** [review]
tested locally

**Pull request merged**
