### PR TITLE
Refactored the valueSetsForCodeService function to pass back only the…

### PR DESCRIPTION
**Pull request by jbradl11**
… specific versions of value sets that are linked to the measure; Removed  version of value sets in the ELM before passing into the execution engine, since we are passing in the correct version of the valueSet, leaving the specified version in the ELM can cause a mismatch of valueset versions.

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] JIRA ticket for this PR:
- [x] JIRA ticket links to this PR: https://jira.mitre.org/browse/BONNIE-1250
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] Code coverage has not gone down and all code touched or added is covered. 
     * See [front-end testing instructions](https://github.com/projecttacoma/bonnie/wiki/Testing#frontend-testing) for getting coverage for front-end tests
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [x] Automated regression test(s) pass
          A few expected failures. Please confirm these results.
          -  Epecqmama  
                  CMS157v6 - 3 patients are failing due to codes being outdated. They need to remove the 
                        code on the Procedure performed / update the code.
           -  NCQA2: 
                  CMS164v6 - 1 patient is failing. Medication Active Code needs to be updated. On that 
                       Patient (NUMERPass ASAOvlpMP&EstOffVisitInMP)
                  CMS156v6 - Number of patients are failing due to using codes that do not exist in the 
                       value sets defined.

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA test links: N/A
- [x] Justification for using JIRA tests: N/A
- [x] JIRA tests have been added to sprint N/A

**Reviewer 1:**

Name: @losborne 
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [X] JIRA tests have been run and pass N/A
- [X] You agree with the justification for use of JIRA tests or have provided input on why you disagree N/A

**Reviewer 2:**

Name: @c-monkey
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [X] JIRA tests have been run and pass N/A
- [X] You agree with the justification for use of JIRA tests or have provided input on why you disagree N/A

### CODE REVIEW

**Comment by lukoktonos** [comment]
Found additional regressions on NCQA:
CMS154v6 has 4 more patients failing due to using codes that do not exist in the
value sets defined.
To fix, go into the patient, follow the failing logic to find the data criteria that should be passing, confirm that the code (i.e. SNOMED-CT: 54150003) is not in the Value Set in the terminology section, and remove the code.  It should auto-repopulate, causing the patient to now pass.

**Review by lukoktonos — DISMISSED** [review]
Code looks good--tests pass including regression (other than the regressions mentioned on the conversation page).

Issue in JIRA ticket is resolved or resolvable with the manual update described on conversation page.

Dashboard load performance greatly increased.

**Review by c-monkey — DISMISSED** [review]
Fixes issues as described above. Tests pass. Code changes look good.

**Review by c-monkey — APPROVED** [review]
I think Travis was borked yesterday. Restarted this morning and are green.

**Review by lukoktonos — APPROVED** [review]
Re-approving after travis fix.

**Pull request merged**
