### PR TITLE
disabled download bundle button

### PR DESCRIPTION
**Pull request by c-monkey**
Hid the download bundle button as this currently doesn't work for CQL-based measures.

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [X] This pull request describes why these changes were made.
- [X] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1107
- [x] JIRA ticket links to this PR
- [X] Code diff has been done and been reviewed
- [X] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [X] Tests are included and test edge cases
- [X] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [X] JIRA test links: N/A
- [X] Justification for using JIRA tests: N/A
- [X] JIRA tests have been added to sprint

**Reviewer 1:**
- [x] Code is maintainable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA tests have been run and pass
- [x] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**
- [x] Code is maintainable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA tests have been run and pass
- [x] You agree with the justification for use of JIRA tests or have provided input on why you disagree

### CODE REVIEW

**Review by mayerm94 — CHANGES_REQUESTED** [review]
The exportBundleDialog modal is still loaded by the page (though never shown). /assets/views/export_bundle_view.js and /assets/templates/users/export_bundle.js might be able to be removed?

**Comment by alexanderelliott121** [comment]
Wasn't there discussion of disabling the endpoint in the backend?

**Review by alexanderelliott121 — CHANGES_REQUESTED** [review]
Remove backend endpoint so that you can't simulate a call.

**Comment by c-monkey** [comment]
I certainly can do the changes you two requested. I carefully added unit tests that show the button is hidden and the route is gone - you can't activate the back-end service.

Since this is a feature that is merely being temporarily disabled - we need to add the button back in - I chose the less invasive changes. Do you disagree that my tests are complete? If we are going to just rip all this code out, we need to make sure it is documented for Cypress because they will need to undo the entire PR.

**Comment by mayerm94** [comment]
(Regarding my previous comment) Maybe the files don't need to be deleted if there is a way to keep the server from sending the modal to the client.

**Comment by c-monkey** [comment]
@mayerm94 okay, removed modal from measures view; note the model is still in the users view, which seems fine since admins don't care if we have a temporarily broken button

@alexanderelliott121 does test "bundle download" in users_controller_test.rb satisfy your concern?

**Review by mayerm94 — DISMISSED** [review]

**Review by alexanderelliott121 — DISMISSED** [review]

**Comment by c-monkey** [comment]
just rebased

**Review by mayerm94 — DISMISSED** [review]
Changes look good, tests and regression pass.

**Review by alexanderelliott121 — DISMISSED** [review]

**Comment by c-monkey** [comment]
Merged in cql4bonnie and fixed 3 warnings

**Review by mayerm94 — APPROVED** [review]

**Review by alexanderelliott121 — APPROVED** [review]

**Pull request merged**
