### PR TITLE
Add support for Ends Concurrent with Start / Starts Concurrent with End

### PR DESCRIPTION
**Pull request by pkmitre**
When rendering a measure, correctly expand ECWS and SCWE into the appropriate readable text

### CODE REVIEW

**Comment by jtferns** [comment]
Do you have a measure that can be used to test this?

**Comment by pkmitre** [comment]
The IPP of CMS56v3 contains a concurrent with measure period clause

**Comment by jtferns** [comment]
Testing this with the final [CMS56v3 bundle](http://jira.oncprojectracking.org/secure/attachment/16660/CMS56v3_Final_5.2.14.zip) produced the following from the IPP logic:
- `ends after start of "Measurement Period"` from the human readable now maps correctly
- `ends concurrent with "Measurement Start Date"` from the human readable maps to `ends concurrent with "Measurement Period"`, which reads incorrectly in the population logic view

Is the Measurement Start Date mapping issue addressable within this story?

**Comment by pkmitre** [comment]
Looks like I neglected to push a commit that updates the version of health-data-standards, which contains the bulk of the fix; I've done that now.

**Pull request merged**
