### PR TITLE
Generalized library functionRef fix to cover expressionRefs too

### PR DESCRIPTION
**Pull request by hossenlopp**
This fixes coverage issues with some library expression references. It renames the helper function made for the functionRef fix and generalizes the fix to expressionRefs too.

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] JIRA ticket for this PR:  https://jira.mitre.org/browse/BONNIE-1185
- [x] JIRA ticket links to this PR
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] Code coverage has not gone down and all code touched or added is covered. 
     * See [front-end testing instructions](https://github.com/projecttacoma/bonnie/wiki/Testing#frontend-testing) for getting coverage for front-end tests
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [x] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA test links:  N/A
- [x] Justification for using JIRA tests:   N/A
- [x] JIRA tests have been added to sprint  N/A

**Reviewer 1:**

Name:
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA tests have been run and pass
- [x] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name: @losborne
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA tests have been run and pass
- [x] You agree with the justification for use of JIRA tests or have provided input on why you disagree

### CODE REVIEW

**Review by lukoktonos — DISMISSED** [review]
New test looks good, just need to fix the other breaking Travis test.

**Review by jbradl11 — DISMISSED** [review]
Agree with Luke. Everything looks good except for broken test.

**Comment by hossenlopp** [comment]
Added more tests to cover the new cases with the library expressionRefs. We had a discussion in the lab and decided to skip the test that is randomly failing. The test fails in `cql4bonnie` if you run it alone. We couldn't find any reason why adding tests or fixtures made that other test fail. We will replace it with an equivalent CQL test when time permits.

**Review by mayerm94 — APPROVED** [review]
New tests make sense, I agree with the rationale behind changing the QDM coverage test so that it is ignored.

**Review by jbradl11 — APPROVED** [review]
Code looks goods, tests now pass.

**Review by lukoktonos — APPROVED** [review]
Looks good.  I agree with making the failing test pending and replacing it with a CQL test at a future time.

**Pull request merged**
