### PR TITLE
Fix missing fieldset for 508 compliance

### PR DESCRIPTION
**Pull request by lukoktonos**
This pull request addresses an issue with 508 compliance--the checkboxes for "Expected Values" were not properly enclosed in a fieldset, which is used by screen readers.

- Added fieldset for Expected Values
- Moved "Expected Values" to be the legend for the fieldset because it was throwing a flag for 508 compliance as well.  
- Changed the styling of legend to match the previous styling.

Pull requests into Bonnie require the following. (Reviewer should :heavy_check_mark:*when done*):

Submitter:

- [X] This pull request describes *why* these changes were made.
- [ ] Tests are included and test edge cases (N/A)
- [X] Link to JIRA test(s), if used: https://jira.mitre.org/browse/BONNIE-1104
- [X] JIRA test(s) have been added to sprint, if used
- [X] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1022
- [ ] JIRA ticket links to this PR. (N/A)
- [ ] Automated regression test(s) pass (if applicable): (N/A)

Reviewer 1 (@jbradl11):
- [x] The code is maintainable
- [x] The code reuses code or resources within the project ecosystem where applicable
- [x] The code achieves its purpose
- [x] The tests appropriately test edge cases
- [x] The tests pass

Reviewer 2 (@holmesie):
- [x] The code is maintainable
- [x] The code reuses code or resources within the project ecosystem where applicable
- [x] The code achieves its purpose
- [x] The tests appropriately test edge cases
- [x] The tests pass

### CODE REVIEW

**Review by ssayer — DISMISSED** [review]
I'll leave it to @holmesie to review the quality of the template changes, but the markup looks good and it passes 508 tests

**Comment by lukoktonos** [comment]
Add `?w=1` to the end of the URL for the "Files Changed" tab to ignore the whitespace changes for this one--had to indent a big block of code, so it looks messy without that.

**Review by holmesie — CHANGES_REQUESTED** [review]
Overall, looks good. One small thing:

Here is what expected looked like before for me:
before1

And now, after:
after1

If you put lines 23-24 between a `<div class="form-group"></div>`, like the isEoC stuff above, things seem to align left properly.

**Review by holmesie — APPROVED** [review]
Changes addressed; looks good to me.

**Review by jbradl11 — APPROVED** [review]
Code changes make sense. I cannot reproduce the 508 issue to begin with, however adding a fieldset and a div (which is all this does) doesn't have any negative effects.

**Pull request merged**
