### PR TITLE
Bonnie 1525

### PR DESCRIPTION
**Pull request by mayerm94**
This PR re-enables the QRDA export functionality and updates the QRDA version of the exports to r5.

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1525
- [ ] JIRA ticket links to this PR
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) ) NA
- [] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 

Branch | Back End Coverage | Front End Coverage
-- | -- | --
master | [Paste Output Here] | [Paste Screenshot Here]
[New Branch] | [Paste Output Here] | image

- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA test links: NA
- [x] Justification for using JIRA tests: NA
- [x] JIRA tests have been added to sprint NA

**Reviewer 1:**

Name: @jbradl11 
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [X] JIRA tests have been run and pass - N/A
- [X] You agree with the justification for use of JIRA tests or have provided input on why you disagree - N/A

**Reviewer 2:**

Name: @c-monkey
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [X] JIRA tests have been run and pass - N/A
- [X] You agree with the justification for use of JIRA tests or have provided input on why you disagree - N/A

### CODE REVIEW

**Review by c-monkey — APPROVED** [review]
Tests pass. https://github.com/projecttacoma/bonnie/pull/979 correctly reverted. QRDA exports seem to work. Gemfile changes will need to be updated when merging. Also we will need to bump the HDS version for the next release.

**Comment by jbradl11** [comment]
Tests appear to be failing on travis and locally for me, is this expected? Also, the diff looks a little odd to me. When you are available lets talk about this PR.

**Review by c-monkey — CHANGES_REQUESTED** [review]
Broken for me, too, I figured @mayerm94 was still working on it. I'll remove my review since it didn't auto-clear.

**Comment by mayerm94** [comment]
The diff is screwed up because my change of PR base did not go as I planned. Redoing this so only my changes will appear

**Pull request closed without merging**
