### PR TITLE
Updated Bonnie user guide to reflect Bonnie version 1.5

### PR DESCRIPTION
**Pull request by c-monkey**
Approved by Shanna 12/5/2016

### CODE REVIEW

**Comment by thecristen** [comment]
I'd like to review this. Since git can't provide line-by-line diffs for the document... are there particular sections I should be looking at?

**Comment by c-monkey** [comment]
The changes in  the "update_user_docs_1-5" branch continue on from DPC15038's changes, while this "final_user_guide_1_5" branch is a copy with intent to quickly insert the Editor's November 18th version into the master branch for deployment. There are a lot of changes through the revisions from Harold and the Editor, so I can't succinctly summarize.

**Review by edeyoung — CHANGES_REQUESTED** [review]
The public release number needs to be added. Harold is managing this.

**Comment by edeyoung** [comment]
@thecristen this needs to be updated with the measure_history information. I believe that Chris has a draft of that he's working on. Please review that version of this document as this version of the document has already gone to harold, the editor, and the sponsor for approval.

A good way to see differences would be through Microsoft's document compare tool in Word.

**Comment by c-monkey** [comment]
I am clearly a github newbie. I rebased on master, but it added a bunch of files to the pull request. Is this normal? I didn't do a "-f" --- can I do that now?

**Review by edeyoung — APPROVED** [review]

**Pull request merged**
