### PR TITLE
Fixed ordering of populations to match human readable

### PR DESCRIPTION
**Pull request by hossenlopp**
This fixes the ordering of populations in the logic view to match the MAT human readable. Unit tests were updated. An additional a test was added to cover the change in order for proportion measures. Note that there was a broken fixture that was fixed. It had an old/faulty populations_cql_map.

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1100
- [x] JIRA ticket links to this PR
- [x] Code diff has been done and been reviewed
- [x] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced. N/A because code that changes the eventual ordering shouldn't change 508 things.
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA test links: N/A
- [x] Justification for using JIRA tests: N/A
- [x] JIRA tests have been added to sprint N/A

**Reviewer 1:**

Name:
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA tests have been run and pass
- [x] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name: @losborne
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA tests have been run and pass (N/A)
- [x] You agree with the justification for use of JIRA tests or have provided input on why you disagree (N/A)

### CODE REVIEW

**Review by jbradl11 — APPROVED** [review]
Simple fix, tests pass and look good.

**Review by lukoktonos — APPROVED** [review]
Changes look good.  Tests cover changes and pass.  Approved.

**Comment by edeyoung** [comment]
Hoss, do you have corresponding MAT packages for these measures that this has been compared against just as a visual double-check?

**Comment by hossenlopp** [comment]
@edeyoung I used a handful of packages in our example 5.4 repository.

One thing to note. The human readable puts the STRAT at the bottom for some reason. I didn't change that because it makes more sense at the top.

**Pull request merged**
