### PR TITLE
Patient builder- merged down into develop

### PR DESCRIPTION
**Pull request by rdingwell**
Someone with more familiarity with the work going on in develop should check this out before merging into develop

### CODE REVIEW

**Comment by carpeliam** [comment]
huh... so a lot of this stuff has already been merged into develop (I think everything except @rdingwell's 5 recent commits), can we shrink this pull request down to only include new commits?

**Comment by pkmitre** [comment]
The commits in common also have different SHA1s, because the original merge was on a rebase; I think I'll just cherry pick the newer commits.

**Comment by pkmitre** [comment]
Cherry-picked into develop and pushed to github

**Comment by carpeliam** [comment]
@pkmitre are you ok with deleting the remote copy of the `patient_builder` branch?

**Comment by pkmitre** [comment]
@carpeliam I'd like to ask Rob to take a look at whether I did the merge correctly first, but then yes, absolutely.

**Comment by carpeliam** [comment]
:+1:

**Pull request closed without merging**
