### PR TITLE
Episode based results and measure population exclusion

### PR DESCRIPTION
**Pull request by hossenlopp**
For episode of care measures, track the population membership per episode, building a new structure, episode_results, that looks just like the population_results but keyed by the episode id.
This makes use of the episode based results for the patient level counts.

This also takes care of filtering out episodes that should not be "observed" because they are in the MSRPOPLEX. The PR that fixes the input box counts for MSRPOPLEX has been cherrypicked in.

The injected ELM to do the observation has been improved to return a list of tuples of the episode and the observed value. This allows us to match the observation with the episode.

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1224 and https://jira.mitre.org/browse/BONNIE-1234
- [x] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced. N/A No UI Changes.
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * See [front-end testing instructions](https://github.com/projecttacoma/bonnie/wiki/Testing#frontend-testing) for getting coverage for front-end tests
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA test links: N/A
- [x] Justification for using JIRA tests: N/A
- [x] JIRA tests have been added to sprint N/A

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

### CODE REVIEW

**Comment by mayerm94** [comment]
Ran regression on this branch, 10 regressions across 3 measures all in the same account

**Comment by hossenlopp** [comment]
The decision was made to hold off on implementing the MSRPOPLEX clearing of observation values.  But this also fixes the DENEX oddities with episodes. Perhaps we can simply remove the clearing of the observ for MSRPOPLEX hit and integrate this fix. Thoughts @edeyoung?

**Comment by edeyoung** [comment]
I like that idea

**Comment by edeyoung** [comment]
Closing - merged into master without the MSRPOPLEX changes. Need to go into v2.1 and uncomment the MSRPOPLEX changes. This PR is therefore out of date and can be closed.

**Pull request closed without merging**
