### PR TITLE
'meaningful use' -> 'CMS quality reporting program'

### PR DESCRIPTION
**Pull request by lukoktonos**
This change is to update the terminology from 'meaningful use' to 'CMS quality reporting program.

image

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [X] This pull request describes why these changes were made.
- [X] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1113
- [x] JIRA ticket links to this PR
- [X] Code diff has been done and been reviewed
- [X] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [X] Tests are included and test edge cases (N/A: too simple of a change to test)
- [X] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [X] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [X] JIRA test links: (N/A)
- [X] Justification for using JIRA tests: (N/A)
- [X] JIRA tests have been added to sprint (N/A)

**Reviewer 1:**

Name: @c-monkey
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases - N/A
- [x] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA tests have been run and pass - N/A
- [x] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name: @hossenlopp 
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases N/A
- [x] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA tests have been run and pass N/A
- [x] You agree with the justification for use of JIRA tests or have provided input on why you disagree

### CODE REVIEW

**Comment by edeyoung** [comment]
@c-monkey @hossenlopp Bridget has ok'd this modification. Please review.

**Review by hossenlopp — APPROVED** [review]

**Comment by hossenlopp** [comment]
I agree with not needing tests for this. I did look to see if there were any references to MU while logged into bonnie. Couldn't find any.

**Comment by hossenlopp** [comment]
Actually I think i want to take back my approval.... "quality reporting" doesn't cause word wrap so it knocks that last big icon out of line. Would suggest adding a `<br/>` to force a new line.

**Comment by hossenlopp** [comment]
Here is what it would look like with a `<br/>` added in there.
screen shot 2017-10-16 at 10 08 09 am

**Review by hossenlopp — CHANGES_REQUESTED** [review]
Suggesting a line break.

**Review by hossenlopp — APPROVED** [review]

**Review by c-monkey — APPROVED** [review]

**Pull request merged**
