### PR TITLE
Toggle measure visualization in measure view

### PR DESCRIPTION
**Pull request by jtferns**
#### Story
- https://www.pivotaltracker.com/story/show/65020512
#### Notes
- added button to Measure settings button group for toggling measure visualization
- added fix for height within each patient population
- updated styling to reflect overall patients coverage in visualization
#### Screenshots
- measure view without viz toggle
  - screen shot 2014-03-17 at 1 22 09 pm
- measure view with viz toggle
  - screen shot 2014-03-17 at 1 22 17 pm

### CODE REVIEW

**Comment by pkmitre** [comment]
Some quick initial thoughts and questions:
- There's some weird tabbing going on in some of the files
- "D3 VIZ" doesn't seem like an appropriate label for the button
- Some variables are being explicitly placed on `window` here and there; is that required?
- The "autotype" JavaScript library is added in this pull request, but I don't see it used anywhere; is it necessary?

**Comment by jtferns** [comment]
I left a lot of the original code from 281e89ff3aa3bb65eb0892505def5edca9cfeee8 the same, with tweaks for functionality.
- I tried mass-fixing the tabs but it gave js compilation errors, so I left it as-is; I will re-attempt this to clean it up
- I am open to suggestions for a button name, does "Chords View" work?
- I am unsure about <code>window</code> usage, a lot of that code is beyond my current understanding for d3/front-end organization
- I will check with Andrew, I don't think it's required but it was in the above branch when I started this story

**Comment by jtferns** [comment]
Rebased on master, and did the following:
- fixed tabs in <code>measure_visual.js</code>
- changed button name to "Chords View", still open to suggestions
- removed autotype.js from vendor/assets

**Comment by jtferns** [comment]
Closing this outdated pull request, replaced with https://github.com/projecttacoma/bonnie/pull/367.

**Pull request closed without merging**
