### PR TITLE
duplicated fixtures from cql_testing_overhaul branch for use in new tests

### PR DESCRIPTION
**Pull request by c-monkey**
Tests from `cql_testing_overhaul` branch as of PR #948 

This doesn't delete or change any existing fixtures in master so we can easily integrate with cql_testing_overhaul w/out merge conflicts.

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [X] This pull request describes why these changes were made.
- [X] This PR is into the correct branch.
- [X] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1278
- [x] JIRA ticket links to this PR
- [X] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [X] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [X] Tests are included and test edge cases
- [X] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [X] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [X] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [X] JIRA test links: N/A
- [X] Justification for using JIRA tests: N/A
- [X] JIRA tests have been added to sprint N/A

**Reviewer 1:**

Name: @hossenlopp 
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases N/A, it's just fixtures
- [x] You have tried to break the code N/A, it's just fixtures that are not being used

If JIRA tests were used to supplement or replace automated tests:
- [X] JIRA tests have been run and pass N/A
- [X] You agree with the justification for use of JIRA tests or have provided input on why you disagree N/A

**Reviewer 2:**

Name: @losborne 
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [X] JIRA tests have been run and pass N/A
- [X] You agree with the justification for use of JIRA tests or have provided input on why you disagree N/A

### CODE REVIEW

**Review by hossenlopp — CHANGES_REQUESTED** [review]
The README files next to the fixtures with instructions for updating them were not updated.

**Comment by c-monkey** [comment]
I am hesitant to make that change, as the export script used to generate these fixtures is also from the branch that #948 is in, one can't make these fixtures using the master branch. I don't want changes in the README on the master branch to conflict with changes made on the reorganization branch.

**Review by hossenlopp — DISMISSED** [review]
I agree with @c-monkey's reasoning for not updating the READMEs right now.

**Review by lukoktonos — COMMENTED** [review]
It looks like CMS160 just had one more patient added on the cql_testing_overhaul branch recently, perhaps we should pull that in as well so we don't have to later.

**Comment by c-monkey** [comment]
@losborne @hossenlopp Updated from latest database.

**Review by hossenlopp — APPROVED** [review]

**Review by lukoktonos — APPROVED** [review]

**Pull request merged**
