### PR TITLE
cql4bonnie dependency updates

### PR DESCRIPTION
**Pull request by holmesie**
Updates to Bonnie dependencies. Ported from `master` into `cql4bonnie` to bring Gem versions up to date.

The Gemfile has been temporarily set to point to the corresponding branches in bonnie_bundler and HDS, which are:
https://github.com/projecttacoma/bonnie_bundler/pull/114
https://github.com/projectcypress/health-data-standards/tree/cql4bonnie_on_mongoid5_adam

To test this, run through the deployment tests located here:
https://jira.mitre.org/secure/enav/#?query=project%20%3D%20%22BONNIE%22%20AND%20fixVersion%20%3D%20%22Unscheduled%22%20AND%20cycleName%20in%20(%22gemfile%20updates%22)

---

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-897
- [x] Code diff has been done and been reviewed
- [x] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced. N/A
- [x] Tests are included and test edge cases
   Existing automated tests and manual tests for deployment
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
   Reviewers will need to support running the manual tests
- [x] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA test links: https://jira.mitre.org/secure/enav/#?query=project%20%3D%20%22BONNIE%22%20AND%20fixVersion%20%3D%20%22Unscheduled%22%20AND%20cycleName%20in%20(%22gemfile%20updates%22)
- [x] Justification for using JIRA tests: Running the set of manual tests to ensure that this doesn't break expected behavior.
- [x] JIRA tests have been added to sprint N/A

**Reviewer 1:**

Name: @hossenlopp
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA tests have been run and pass
- [x] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

### CODE REVIEW

**Comment by mayerm94** [comment]
When I upload 
[cqltest68_v5_1_artifacts.zip](https://github.com/projecttacoma/bonnie/files/1376481/cqltest68_v5_1_artifacts.zip) There is a discrepancy between staging and this PR in how the measure version is displayed (Worth noting that it is displayed differently in the measures view too)

Before:
screen shot 2017-10-11 at 12 44 13 pm

After:
screen shot 2017-10-11 at 12 44 00 pm

**Comment by hossenlopp** [comment]
Oh hey! It's semantic version numbers that we added into HDS and Bonnie during measure history development.

**Comment by mayerm94** [comment]
I ran all of the JIRA tests. One fail, measure won't load so it is a real fail that needs to be investigated. I ran the automated regression tests, they showed no regressions in coverage or pass/fail ratio.

**Comment by edeyoung** [comment]
hm. we hid that in the main view of the measure though - added some logic so it still looked clean
we should port that over, i think.

**Comment by edeyoung** [comment]
matt, can you add the failing test and accompanying information to the internal ticket? thanks!

**Comment by mayerm94** [comment]
Re-ran regression test. All is good

**Review by mayerm94 — DISMISSED** [review]
Regression works, JIRA tests have not be run on the most recent commit but they were run for the previous two. On the highly unlikely chance that there is a breaking change we will catch it when we test the full JIRA suite during staging deployment.

**Review by hossenlopp — DISMISSED** [review]
This branch is behind `cql4bonnie` it has one failing test that is picked up by travis and local runs. It looks like the test was modified in the QDM removal that this branch doesn't have.

**Review by mayerm94 — DISMISSED** [review]

**Review by hossenlopp — DISMISSED** [review]

**Review by hossenlopp — APPROVED** [review]
regression test passes!

**Review by mayerm94 — APPROVED** [review]
Local tests + regression pass

**Pull request merged**
