### PR TITLE
Update Medications for Cumulative Medication Duration calculations

### PR DESCRIPTION
**Pull request by jtferns**
~~_Note: This feature requires the updated https://github.com/pophealth/hqmf2js/commit/6a7b24e54580d863f28fe90d99763932f57b8949 for accurate CMD calculations._~~
#### Story
- https://www.pivotaltracker.com/story/show/70168122
#### Notes
- removed [ DOSE, FREQUENCY, CUMULATIVE_MEDICATION_DURATION ] from Medication field values
- added Dose (dose_value, dose_unit) and Frequency (administrationTiming; frequency_value, frequency_unit) to medication patient data criteria window
- added Fulfillments (dispense_datetime, quantity_dispensed_value, quantity_dispensed_unit) to medication patient data criteria
- proposed testing strategy
  - checkout this branch
  - stop any running server(s)
  - update bundle via <code>bundle install</code>
  - clear the local cache via <code>rm -rf tmp/cache/</code>
  - launch Bonnie and navigate to <code>CMS156v2</code>
  - create a new patient with the following criteria
    - first: test
    - last: patient
    - birthdate: 01/01/1900
    - expected values: <code>IPP</code>, <code>DEN</code>
    - Encounter Performed: Office Visit
      - start date: xx/xx/2012
      - end date: xx/xx/2012
    - Medication Order: High-Risk Medications With Days Supply Criteria
      - dose: 5 mg
      - frequency: 1 day(s)
      - fulfillment(s)
        - start date: xx/xx/2012
        - quantity dispensed: < 450 mg for failing, >= 450 mg for passing, across all fulfillments
  - you can tweak the medication dosage, frequency, and fulfillments to test CMD calculations accordingly

### CODE REVIEW

**Comment by jtferns** [comment]
I did not include the CMD calculation update ( https://github.com/pophealth/hqmf2js/commit/6a7b24e54580d863f28fe90d99763932f57b8949 ) because I could not get it to work correctly.

I attempted to update bonnie's Gemfile to point to hqmf2js master, to update bonnie_bundler's Gemfile to point to hqmf2js master, and both respectively; no combination seemed to have worked, so I left it out.

If someone can point me to where I can update hqmf2js, I will add it to this branch and CMD should calculate correctly.

**Comment by jtferns** [comment]
I finally got the calculations to update by running <code>rm -rf tmp/cache/</code> and restarting my local server after updating the Gemfile...now CMD works as expected. ~~; will update the pull request with a testing strategy.~~

**Comment by pkmitre** [comment]
Re: testing strategy, should it be quantity dispensed > 450 mg to get the numerator to turn green?

**Comment by pkmitre** [comment]
I see some strange behavior: when looking to click the + for fulfillments, 1) the button doesn't become clickable until the input field is blurred, so typing an input and then clicking doesn't work, you have to click again because the + only then becomes enabled, and 2) when then clicking on the enabled +, the new fulfillment does get added, but then the calendar popup in the fulfillment section is activated.

**Comment by jtferns** [comment]
Yes, in the proposed testing strategy, any value of quantity dispensed >= 450 across the total fulfillment history should qualify the patient for the numerator.

I will address the two strange behavior issues in another commit, soon.

**Pull request merged**
