### PR TITLE
add cms_id changes back to move_patients and update_source_data_crite…

### PR DESCRIPTION
**Pull request by lukoktonos**
Due to the discovery that the import_patients rake task updates both hqmf_set_id and cms_id, this PR adds back in cms_id updating for the move_patients function as well as the update_source_data_criteria rake task.

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1233
- [x] JIRA ticket links to this PR
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] N/A If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] Code coverage has not gone down and all code touched or added is covered. 
(Coverage went down due to bonnie_run_once lines added. All code not in bonnie_run_once is covered.)
- [x] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [x] N/A JIRA test links:
- [x] N/A Justification for using JIRA tests:
- [x] N/A JIRA tests have been added to sprint

**Reviewer 1:** @mayerm94

Name:
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA tests have been run and pass N/A
- [x] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA tests have been run and pass
- [x] You agree with the justification for use of JIRA tests or have provided input on why you disagree

### CODE REVIEW

**Review by mayerm94 — DISMISSED** [review]
Changes make sense. DB compare modified document count equals that which was reported by the rake task. 2582=2582
screen shot 2018-01-08 at 12 09 40 pm

**Review by jbradl11 — DISMISSED** [review]
Code looks good. Tests pass. Issue is resolved with the rake task. Ran a diff on the Patient Collection before and after the Rake task: changes are expected.

**Comment by jbradl11** [comment]
Based on our earlier discussion in the sprint planning meeting. Should these results be investigated? 

image

**Comment by lukoktonos** [comment]
@jbradl11 The `cms_id` updated count is higher than the `hqmf_set_id` count because patients' `source_data_criteria` `cms_id`s are not updated on measure update or re-upload.

Currently https://github.com/projecttacoma/bonnie/blob/cql4bonnie/lib/tasks/bonnie.rake `import_patients` does update the `cms_id`, but there are still a lot of out-of-date `cms_id`s on the database.

Based on our discussion at sprint planning, it makes sense to leave out this change, as we do not have a compelling enough reason for needing to update them.

@mayerm94 @edeyoung your thoughts?

**Review by mayerm94 — COMMENTED** [review]
The reason why I think that cms_id should be updated (in addition to the fact that we update it on patient import) is that in the toPatientDataCriteria function inside datacriteria.js.coffee, the cms_id is copied from the measure.            'cms_id:@collection.parent.get('cms_id')' I don't see anywhere where this field is used, so I don't know what sort of consequences could result from this field being incorrect.

**Comment by edeyoung** [comment]
This is a toughie - I'd say to update it. It makes sense as a field that changes on measure change (in addition to what Matt wrote). Let's update it, and then check a few of the cases where cms_id is updated but hqmf_set_id is not and confirm that we see expected behavior

**Comment by jbradl11** [comment]
So should we also update this field on measure update / re-upload (for consistency)? Seeing that there are many patients whose `cms_id` are outdated, this will be a reoccurring issue. Also just a note. I don't think there was a reason to updating the `cms_id` in the patient import script. I don't know what this field is for.

**Comment by lukoktonos** [comment]
Closing after discussion to deal with making the cms_id updates consistent between rake tasks and measure upload/update as part of a 2.1 release.

**Pull request closed without merging**
