### PR TITLE
Target Rubocop at Ruby 2.3; Added rbenv ruby version config

### PR DESCRIPTION
**Pull request by holmesie**
For those who use rbenv, this config makes it easier to maintain the ideal Ruby version for Bonnie, while still being able to use a different global version.

This PR also fixes the rubocop target ruby version, and adds the new rubocop complaints to rubocop-todo.yml.

---

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] <s>JIRA ticket for this PR:</s>
- [x] <s>JIRA ticket links to this PR</s>
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] <s>If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.</s>
- [x] <s>Tests are included and test edge cases</s>
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] <s>Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )</s>
- [x] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 

**Reviewer 1:**

Name:
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

**Reviewer 2:**

Name: @losborne
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

### CODE REVIEW

**Review by lukoktonos — DISMISSED** [review]
Changes make sense.  Re-generating the rubocop_todo.yml shows no differences.

Interestingly, if we do `rubocop --auto-correct`, there would be only 440 offenses remaining of the 1328 reported.

**Review by jbradl11 — CHANGES_REQUESTED** [review]
I am seeing differences in "Offense count" .rubocop_todo.yml when running 'rubocop --auto-gen-config' locally.

**Comment by holmesie** [comment]
Right, these differences (new rubocop complaints) were caused by things that have been merged into master since my original push for this PR. I've pushed an updated rubocop_todo to address these.

**Review by lukoktonos — APPROVED** [review]
Looks good!

**Review by jbradl11 — APPROVED** [review]
Looks good.

**Pull request merged**
