### PR TITLE
Edit population titles

### PR DESCRIPTION
**Pull request by thecristen**
Replacing earlier PR #395 
## Story
- https://www.pivotaltracker.com/story/show/75134126
## Notes

Took the inline editing example from the edit user functionality in the admin page, seems to work pretty well here.
## Screenshot

screenshot 2014-09-17 09 41 16

### CODE REVIEW

**Comment by pkmitre** [comment]
Looks great! Do you think that allowing the title to be saved using the enter key is worth while?

**Comment by thecristen** [comment]
Yeah, I think that would be worthwhile. Good catch!

**Comment by pkmitre** [comment]
Just noticed one more thing: when a browser is in a bit wider configuration, the text box takes up a relatively small amount of the available space:
screen shot 2014-10-08 at 10 05 16 am
It would be nice if the text box took as much space as available.

**Comment by thecristen** [comment]
Here's the latest! 
image

**Pull request merged**
