### PR TITLE
Updated Bonnie User Guide for v1.5

### PR DESCRIPTION
**Pull request by DPC15038**
Changelog

Figure 9: Measure View
1. Added in the Patient Dashboard Toolbar, and the Measure Upload History Link
    -> Added in explanations for these new elements on the previous page
    -> Increased icon numbers in next figure (Figure 10) from 17 and 18, to 21 and 22
       to account for these new elements
Heading 4.9: Updating a Measure  
1. Added Figure 14 to show a Measure Upload
    -> Added Alternate text
    -> Added a description below the Figure

Figure 15: Patient Builder
1. Added Patient Age, Utility Bar, and Upload History Button
    -> Added Icon #6 to describe Patient Age
    -> Explained Icon #6 in the previous page

Figure 17: Builder Patient History
1. Added Utility Bar and Icons 11, 12 and 13
    -> Described Icons 11, 12 and 13 on the previous page

Heading 6: Measure History
1. Added 6.1: Overview of what Measure History is
2. Added Figure 21: Measure Upload History View with Alternate Text
3. Described Figure 21 below the Figure
  -> Added 6.1.1, Logic Changes
  -> Added Figure 22, Logic Changes from an Updated Measure
4. Added 6.2 Patient Compare View 
  -> Added Figure 23: Patient Compare View with Alternate Text

Heading 7: Patient Dashboard
1. Added 7.1L Overview of what Patient Dashboard is
2. Added Figure 24: Patient Dashboard View with Alternate Text
  -> Added Description above Figure 24
3. Added Figure 25

Updated all the Figure/Heading Numbers to account for these changes
Updated Bonnie Version, and Date
Added a separate document with tips for updating the User Guide

### CODE REVIEW

**Comment by mulcahyk** [comment]
Do we want to have links in the document to bring people to where we are referencing?

**Comment by DPC15038** [comment]
@mulcahyk We can, it's pretty easy to change. Should I go back and change them all to link to the figures/headings? What are people's thoughts?

**Comment by mulcahyk** [comment]
I think it would make it easier to get around in the guide.

**Comment by edeyoung** [comment]
These changes have been the foundation for user guide changes.

**Pull request closed without merging**
