### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by rdingwell**
Added rake task to update patient source data criteria with title and description from measure source data criteria.

### CODE REVIEW

**Comment by pkmitre** [comment]
I think that this task should be written to run after using the new DB reset task (rake bonnie:db:reset), which changes record measure_ids from NQF ids to hqmf_set_ids, so

```
measures = Measure.where({measure_id: {"$in" => patient.measure_ids}})
```

should probably be

```
measures = Measure.where({hqmf_set_id: {"$in" => patient.measure_ids}})
```

Possibly of interest, I think that the "in" above can be simplified a bit using Mongoid, so:

```
measures = Measure.in(hqmf_set_id: patient.measure_ids)
```

Also, 

```
Record.where({}).each do |patient|
```

can be written as just

```
Record.each do |patient|
```

**Comment by rdingwell** [comment]
So the patient records are being associated to the version neutral measure id's?

**Comment by pkmitre** [comment]
That's right, that way when a measure developer uploads a newer version of the same measure they keep the existing patient associations.

**Comment by rdingwell** [comment]
Allright.  I'm not sure I agree with that but if Andre is on board ok.   I just think that there will probably be some issues with that approach in practice for updated valuesets and redefinition of data criteria.

**Pull request merged**
