### PR TITLE
BONNIE-1085 Update display to recognize draft valuesets.

### PR DESCRIPTION
**Pull request by alexanderelliott121**
This change was made to ensure that valuesets are correctly loaded according to the following rules:
If draft: use latest draft version, which means looking up with default profile and includeDraft.
Else if verion or profile are specified: use the specified version/profile.
Else: use default profile for lookup.

JIRA at: https://jira.mitre.org/browse/BONNIE-1085
Test at: https://jira.mitre.org/browse/BONNIE-1101
Related PR: https://github.com/projecttacoma/bonnie_bundler/pull/111

Pull requests into Bonnie require the following. (Reviewer should :heavy_check_mark:*when done*):

Submitter:

- [x] This pull request describes *why* these changes were made.
- [x] Tests are included and test edge cases
- [x] Link to JIRA test(s), if used:
- [x] JIRA test(s) have been added to sprint, if used
- [x] JIRA ticket for this PR: 
- [x] JIRA ticket links to this PR.
- [x] Automated regression test(s) pass (if applicable): 

Reviewer 1:
- [x] The code is maintainable
- [x] The code reuses code or resources within the project ecosystem where applicable
- [x] The code achieves its purpose
- [x] The tests appropriately test edge cases
- [x] The tests pass

Reviewer 2:
- [x] The code is maintainable
- [x] The code reuses code or resources within the project ecosystem where applicable
- [x] The code achieves its purpose
- [x] The tests appropriately test edge cases
- [x] The tests pass

### CODE REVIEW

**Comment by alexanderelliott121** [comment]
Updating test in progress.

**Comment by alexanderelliott121** [comment]
Tests have been updated.

**Comment by alexanderelliott121** [comment]
Ready for review attention.

**Comment by holmesie** [comment]
I think this pull request is missing a lot of things... I'm only seeing one line changed...

**Comment by alexanderelliott121** [comment]
This is the front end change that pairs with the back end.

**Comment by holmesie** [comment]
Might want to link to it, and make a comment about that in the description. The description as it is now doesn't correspond to the changes in this PR itself at all.

**Comment by lukoktonos** [comment]
Regression script (with coverage) passes -- all results equal.

**Review by lukoktonos — APPROVED** [review]
Looks good.  See comment on bonnie_bundler PR about unit/JIRA tests.

**Comment by jbradl11** [comment]
@alexanderelliott121 Please see my comment on the bonnie_bundler PR (https://github.com/projecttacoma/bonnie_bundler/pull/111). I think this would be an easy change to test in a unit test.

**Comment by alexanderelliott121** [comment]
Automated tests added to bonnie_bundler.

**Review by jbradl11 — APPROVED** [review]
Looks good. Corresponding Bonnie Bundler PR also looks good.

**Pull request merged**
