### PR TITLE
Bonnie 1300 execution timestamp

### PR DESCRIPTION
**Pull request by jbradl11**
**DO NOT MERGE THIS BEFORE BONNIE-1299**

This PR creates a CQL DateTime (the time of execution) and passes the value into the execution engine, which will allow Bonnie to set all Timezone offsets in the execution engine to "0". Also the CQL functions "Now" and "Today" will match the DateTime that we pass in.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1300
- [x] JIRA ticket links to this PR
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [x] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA test links: N/A
- [x] Justification for using JIRA tests: N/A
- [x] JIRA tests have been added to sprint: N/A

**Reviewer 1:** @mayerm94

Name:
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA tests have been run and pass
- [x] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name: @losborne
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA tests have been run and pass
- [x] You agree with the justification for use of JIRA tests or have provided input on why you disagree

### CODE REVIEW

**Review by mayerm94 — APPROVED** [review]
Changes make sense with execution engine change. Test looks good. New measure makes sense to add and all proper documentation has been updated.

**Review by lukoktonos — CHANGES_REQUESTED** [review]
New measure should be in `special_measures` directory rather than `CQL` (also update README to export to `special_measures` instead of `CQL`).

Measure zip file should be added to `test/fixtures/cql_measure_exports` as per https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing

**Review by lukoktonos — APPROVED** [review]

**Comment by c-monkey** [comment]
@jbradl11 The front end coverage decreased from:

```
Statements   : 56.95% ( 6823/11981 )
Branches     : 39.97% ( 1791/4481 )
Functions    : 47.24% ( 1120/2371 )
Lines        : 54.69% ( 6106/11165 )
```
to:
```
Statements   : 55.03% ( 7757/14095 )
Branches     : 36.33% ( 1886/5191 )
Functions    : 45.12% ( 1272/2819 )
Lines        : 52.55% ( 6851/13036 )
```

Thereby decreasing our coverage beneath the threshold.

**Comment by c-monkey** [comment]
Regression/coverage tests show no changes.

**Pull request merged**
