### PR TITLE
update fixtures with anatomical_location and new drc format

### PR DESCRIPTION
**Pull request by lukoktonos**
This PR is to update the front-end and back-end changes due to recent changes (new drc code format and 'anatomical_location' added).

To update the fixtures, I ran the commands listed in:
Back end: bonnie/test/fixtures/README
Front end: bonnie/spec/javascripts/fixtures/json/README

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1288
- [x] JIRA ticket links to this PR
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced. N/A
- [x] Tests are included and test edge cases N/A
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
NOTE: there are failing back-end and front-end tests, but they match those failing in `cql_testing_overhaul` itself and will be fixed as part of other tasks.
- [x] Code coverage has not gone down and all code touched or added is covered. 
- [x] Automated regression test(s) pass

**Reviewer into feature branch:**

Name: @c-monkey 
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA tests have been run and pass
- [x] You agree with the justification for use of JIRA tests or have provided input on why you disagree

### CODE REVIEW

**Comment by c-monkey** [comment]
There are no changes in test results (front end 79f/175, back end 1f/112). Perhaps you should add a test that fails before and does not fail now?

**Review by c-monkey — CHANGES_REQUESTED** [review]
I see nothing that concerns me, this is a straightforward change.

**Review by c-monkey — APPROVED** [review]
looks good

**Review by c-monkey — CHANGES_REQUESTED** [review]
There is still an error that should be trivial to fix, check out the Travis log:

  1) Failure:
BonnieDbTest#test_download_measure_package [/home/travis/build/projecttacoma/bonnie/test/rake/bonnie_db_test.rb:112]:
In stdout.
--- expected
+++ actual
@@ -1,3 +1,3 @@
 "\e[32m[Success]\e[0m\tbonnie@example.com: measure with HQMF set id A4B9763C-847E-4E02-BB7E-ACC596E90E2C found
-\e[32m[Success]\e[0m\tSuccessfully wrote CMS160v6_bonnie@example.com_2017-10-26.zip
+\e[32m[Success]\e[0m\tSuccessfully wrote CMS160v6_bonnie@example.com_2018-01-11.zip
 "
@hossenlopp thinks this was caused by the force-push changing the filename

**Comment by hossenlopp** [comment]
That test that is failing is testing the download package rake task. Since the fixture was updated, the created_at time on the measure changed. That time is used in the file name it uses for the export. Just update the test to reflect the new time of CMS160 and it should be good to go.

**Review by c-monkey — APPROVED** [review]
Back end tests pass except for fail percentage but that's fixed in another PR. Thanks, Luke

**Pull request merged**
