### PR TITLE
Fix observ msrpoplex

### PR DESCRIPTION
**Pull request by jbradl11**
Second part to fixing Observations with Msrpoplex. Adds and removes OBSERV boxes based on the MSRPOPL and MSRPOPLEX.

### CODE REVIEW

**Review by c-monkey — CHANGES_REQUESTED** [review]
1) measure view works great, tested this change and I'm happy with it.

2) unfortunately, this change introduced an issue with the patient dashboard - it now shows a failure for the OBSERV field

**Review by c-monkey — APPROVED** [review]
tested locally, looks good.

**Review by mayerm94 — APPROVED** [review]
Tested locally

**Comment by c-monkey** [comment]
This is a fix for https://jira.mitre.org/browse/BONNIE-406

**Pull request merged**
