### PR TITLE
Bonnie 976 profile

### PR DESCRIPTION
**Pull request by alexanderelliott121**
JIRA: https://jira.mitre.org/browse/BONNIE-976
Test: https://jira.mitre.org/browse/BONNIE-1030

### CODE REVIEW

**Comment by alexanderelliott121** [comment]
In gemfile, point health-data-standards and bonnie-bundler at BONNIE-976_Profile

**Comment by alexanderelliott121** [comment]
In Gemfile, point health-data-standards at BONNIE-976_Profile

**Review by c-monkey — CHANGES_REQUESTED** [review]
ruby unit tests failing locally even with Gemfile changes

**Comment by alexanderelliott121** [comment]
This is broken, making a new one.

**Pull request closed without merging**
